/*
 * This source file was generated by the Gradle 'init' task
 */
package matrixtranspose;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int[][] arr = new int[3][3];
        int[][] transpose = new int[3][3];
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                System.out.print("Enter matrix index of [" + i + "][" + a + "]: ");
                arr[i][a] = sc.nextInt();
            }
        }
        System.out.println("Normal Matrix is");
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                System.out.print(arr[i][a] + " ");
            }
            System.out.println();
        }
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                transpose[i][a] = arr[a][i];
            }
        }
        System.out.println("Matrix Transpose is");
        for (int i = 0; i < 3; i++) {
            for (int a = 0; a < 3; a++) {
                System.out.print(transpose[i][a] + " ");
            }
            System.out.println();
        }
        sc.close();
    }
}