/*
 * This source file was generated by the Gradle 'init' task
 */
package monthcheck;

import java.util.Scanner;

public class App {
    public static boolean checkInput(int day, int month, int year) {

        if (year < 2500 || year > 2565) {
            return false;
        }
        if (month < 1 || month > 12) {

            return false;
        }
        if (day < 1 || day > getDaysInMonth(month)) {

            return false;
        }
        return true;
    }

    public static int getDaysInMonth(int month) {
        switch (month) {
            case 1:
                return 31;
            case 2: // กุมภาพันธ์
                return 28;
            case 3:
                return 31;
            case 4:
                return 30;
            case 5:
                return 31;
            case 6:
                return 30;
            case 7:
                return 31;
            case 8:
                return 31;
            case 9:
                return 30;
            case 10:
                return 31;
            case 11:
                return 30;
            case 12:
                return 31;
            default:
                return 0;
        }
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        while (true) {
            System.out.print("Enter day: ");
            int day = sc.nextInt();
            System.out.print("Enter month: ");
            int month = sc.nextInt();
            System.out.print("Enter year: ");
            int year = sc.nextInt();
            if (checkInput(day, month, year)) {
                System.out.println("Correct!");
                break;
            } else {
                System.out.println("Wrong value(s)");
            }
        }
        sc.close();
    }
}