/*
 * This source file was generated by the Gradle 'init' task
 */
package primenumber;

import java.util.Scanner;

public class App {
    public static boolean Prime(int n) {
        if (n <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter input number: ");
        int n = sc.nextInt();
        System.out.println("Prime numbers is");
        for (int i = 2; i <= n; i++) {
            if (Prime(i)) {
                System.out.print(i + " ");
            }
        }
        sc.close();
    }
}